160 save the widgets local filters in the layout
debiai/DebiAI pull request #186
Opened 2024-04-08 13:37 UTC by FadyCoding

## Describe your changes
Saved the widgets local filters whenever loading and saving a new layout is done.
## Screenshots (if appropriate):

## Issue ticket number and link
Issue ticker 160
https://github.com/debiai/DebiAI/issues/160
## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have increased the version number in the `frontend/package.json` and `backend/swagger.yaml` files
- [x] I have checked that Black, Flake8, Prettier and Cspell are passing

2024-04-08 13:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/debiai/DebiAI?pullRequest=186) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/debiai/DebiAI?pullRequest=186) before we can accept your contribution.<br/><hr/>**Fady BEKKAR** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/debiai/DebiAI?pullRequest=186) it.</sub>

2024-04-08 13:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/debiai/DebiAI?pullRequest=186) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/debiai/DebiAI?pullRequest=186) before we can accept your contribution.<br/><hr/>**Fady BEKKAR** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/debiai/DebiAI?pullRequest=186) it.</sub>

2024-04-09 08:04 UTC, Tomansion requested changes
Well done
Somme last changes and you're good

2024-04-09 08:04 UTC, Tomansion commented on frontend/src/components/debiai/dataAnalysis/DataAnalysis.vue
> +      // Save the body into a json file
To remove

2024-04-09 11:26 UTC, FadyCoding commented on backend/swagger.yaml
> +  : get:
It added itself on its own. Does not work with it, idk why.

2024-04-09 11:26 UTC, FadyCoding commented on backend/swagger.yaml
> +  : post:
It added itself on its own. Does not work with it, idk why.

2024-04-15 09:37 UTC, Tomansion approved these changes

2024-04-15 09:43 UTC, merged