changed backend directory as python module
debiai/DebiAI pull request #206
Opened 2024-06-10 14:52 UTC by FadyCoding

## Describe your changes

## Screenshots (if appropriate):

## Issue ticket number and link

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have increased the version number in the `frontend/package.json` and `backend/swagger.yaml` files
- [ ] I have checked that Black, Flake8, Prettier and Cspell are passing

2024-07-18 14:00 UTC, Tomansion requested changes
Excellent job :rocket:

2024-07-18 14:01 UTC, Tomansion commented
Complete the pull request description

2024-07-18 14:03 UTC, Tomansion commented on debiaiServer/modules/algoProviders/integratedAlgoProvider/algorithms/regressionErrorMetric.py
:+1:

2024-07-19 08:06 UTC, FadyCoding commented on build_and_run.sh
yes it won't be merged, thank you for noticing it !

2024-07-19 08:08 UTC, FadyCoding commented on README.md
One `README`  will remain for DebiAI and one will be added for debiai-gui, thank you for your comment ?

2024-07-25 10:17 UTC, Tomansion requested changes

2024-07-25 10:17 UTC, Tomansion commented on build_and_run.sh
The file is here again @FadyCoding  ( ͡ᵔ ͜ʖ ͡ᵔ)''

2024-07-25 10:17 UTC, Tomansion commented on run_debiai_server_dev.py
> +websrv.start_server(port=3000, reloader=False, is_dev=True)
reloader=True

2024-07-25 12:38 UTC, Tomansion approved these changes
ᕦ(ò_ó )ᕤ

2024-07-25 12:41 UTC, merged